<?php
if ( ! defined( 'ABSPATH' ) ) {
	die;
}

define( 'PFVI_ADMIN_TEMPLATES', PFVI_ADMIN . DIRECTORY_SEPARATOR . "partials" . DIRECTORY_SEPARATOR );
define( 'PFVI_ADMIN_CSS', PFVI_ADMIN . DIRECTORY_SEPARATOR . "css" . DIRECTORY_SEPARATOR );
define( 'PFVI_ADMIN_IMAGES', PFVI_ADMIN . DIRECTORY_SEPARATOR . "images" . DIRECTORY_SEPARATOR );
define( 'PFVI_ADMIN_IMAGES_URL', PFVI_ADMIN_URL . DIRECTORY_SEPARATOR . "images" . DIRECTORY_SEPARATOR );